### ISSUE TITLE
Is it possible to add a by argument to the bounds?

### ISSUE THREAD

**Issue by flippercy** [AnotherSamWilson/ParBayesianOptimization#10]
Currently the bounds must be a list with vectors specifying the lower and upper bounds of each hyperparameter, such as list(X=c(1, 10)). Is it possible to add a third argument as 'by'? For example, list(X=c(1, 10, 2) indicates that the search should be done among c(1, 3, 5, 7, 9).

Thank you!

**Comment by AnotherSamWilson** [comment]
Not directly, however you can transform the parameter inside your scoring function. Your example would look like:
`bounds <- list(
  "x" = c(1L,5L)
)

scoringFunction <- function(x) {
  x <- x*2-1
  
  # Other Stuff
    
}`

**Comment by flippercy** [comment]
Thank you Samuel!

Sent from my iPhone

On Apr 15, 2020, at 7:44 AM, Samuel Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #10<https://github.com/AnotherSamWilson/ParBayesianOptimization/issues/10>.
