### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by flippercy** [AnotherSamWilson/ParBayesianOptimization#11]
Hi:

I sometimes got the following error message:

'Error encountered while training GP: <the leading minor of order 28 is not positive definite>'

What does it mean?

**Comment by AnotherSamWilson** [comment]
This usually means the process keeps trying to sample approximately the same spot. If you let a process run forever, you will eventually get this error. It should still return the results. If you plot the object, does it show the utility converging?

**Comment by flippercy** [comment]
Probably not. I got this message after the first iteration and the function stopped running.

**Comment by AnotherSamWilson** [comment]
Can you post a reproducible example?

**Comment by flippercy** [comment]
Let me see whether I can find something. I am using the function to tune hyperparameters for an xgboost model. For some parameters such as sample rate, I want the search space be discrete, such as (0.65, 0.7, 0.75, 0.8, 0.85).

When I did the search with a continuous interval like [0.65, 0.85], there was no issue; however, after our conversation yesterday I changed it to [13L, 17L] and made sample_rate = sample_rate*5 in the scoring function, then I got the error message after a couple of iterations.

**Comment by flippercy** [comment]
I am afraid the error is due to the new way I used to generate discrete search space for some hyperparameters. After switching back to the old method, the function runs well.

Later probably I can post a reproducible example with some public data sets.

Thank you.

**Comment by flippercy** [comment]
Hi Mr. Wilson:

I've played with your package in the last two days and understood its logic better. Thank you for the excellent work!

I still got a few error messages occasionally. Probably they were due to the data I used because I could not replicate them using the public data sets I found. Could you explain what they mean, please?

The first one is:

**Starting Epoch 2
  1) Fitting Gaussian Process...
     - Could not obtain meaningful lengthscales.  
2) Running local optimum search...
     - Convergence Not Found. Trying again with tighter parameters...
     - Convergence Not Found. Trying again with tighter parameters...
     - Convergence Not Found. Trying again with tighter parameters...
     - Maximum convergence attempts exceeded - process is probably sampling random points.**

The second one is:

Starting Epoch 2 
  1) Fitting Gaussian Process...
 Returning results so far. Error encountered while training GP: <the leading minor of order 12 (this number varied) is not positive definite> 

Both showed up when the search was at the early stage and far from complete; the utility was not converged and the best value returned was not even close to the optimal value. The process kept running with the first error message but stopped if the second error message popped up.

Any insights?

Appreciate your help!

Yu
