### ISSUE TITLE
starting with initial grid

### ISSUE THREAD

**Issue by MichaelHabiMeier** [AnotherSamWilson/ParBayesianOptimization#18]
Hi
I like your ParBayesianOptimization R-package and started to work with it. While I runned it a couple of times with random initial points, I would now like to start it with a pre-defined initial grid. However, the code seems not to allow for this: if I want to start with an initial grid, I must ommit the initial point value. However, the initial point value must always be greater than the length of the boundary list, which it is not, if I ommit it... Or do I miss something?

Code:
if (missing(initGrid) + missing(initPoints) != 1) stop("Please provide 1 of initGrid or initPoints, but not both.")
if (initPoints <= length(bounds)) stop("initPoints must be greater than the number of FUN inputs.")

Best regards,
michael

**Comment by AnotherSamWilson** [comment]
Oof, this passed the unit tests because you _can_ use an initial grid as long as the scoring function has 4 or less inputs, since the default initPoints is 4. I'll push a fix today. Thanks!
