### ISSUE TITLE
Could we let the function return the performance of initial points as well?

### ISSUE THREAD

**Issue by flippercy** [AnotherSamWilson/ParBayesianOptimization#19]
Currently the bayesOpt function returns the score summary of each iteration but the initial one (iteration 0); is it possible to enable it to return the score summary of the initial iteration, too? Will be helpful when a single iteration takes a lot of time.

Thank you.

**Comment by AnotherSamWilson** [comment]
The ScoreSummary table does return the initial points, they are labeled as Epoch 0.

**Comment by flippercy** [comment]
That’s true but could it also be returned to the console like other iterations following it during the searching ?

Thank you.

Sent from my iPhone

On Oct 14, 2020, at 8:06 AM, Samuel Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


The ScoreSummary table does return the initial points, they are labeled as Epoch 0.
