### ISSUE TITLE
Save and Continue

### ISSUE THREAD

**Issue by Jopinc** [AnotherSamWilson/ParBayesianOptimization#24]
Hi Dears! I'm working with a bayessian optimization using parBayessianOptimization library applied in a classification model using lightGBM. My dataset is a quit big (~2MM rows) so the optimization process last a huge amount of time (more than 24hs). I was wondering if there is a way to stop and save the BayesOpt object and then continue running it later starting from last iteration. Is there a way to do that? Could anyone help me?

In my code I save the bayesOpt object with "saveFile" parameter in a RDS file. 

Opt <- bayesOpt(
  FUN = Custom_Function_Metric
  , bounds = bounds
  , parallel = FALSE
  , initPoints = 20
  , iters.n = 100
  , iters.k = 1
  , plotProgress = TRUE
  , verbose = 2
  , saveFile = paste0("~/cloud/cloud1/Scripts/bayesOpt_",idtest,".RDS")
)

**Comment by AnotherSamWilson** [comment]
You can use the `addIterations` function to continue optimization of a `bayesOpt` object. You can save intermediary steps to a file using the saveFile argument. Make sure the filepath includes the .RDS extension.
