### ISSUE TITLE
Creative Way to Add Constraints 

### ISSUE THREAD

**Issue by swaheera** [AnotherSamWilson/ParBayesianOptimization#41]
```
library(ParBayesianOptimization)

bayesian_function <- function(x1, x2, x3, x4) {
    var_1 <- sin(x1 + x2)
    var_2 <- cos(x1 - x2)
    var_3 <- x1 + x4
    var_4 <- x3 + x4 -7
    goal_1 = sum(var_1 + var_2 + var_3 + var_4)
    
    
    if (var_1 > 0.6 ) {
        goal_1 =999999 }
    else {
        goal_1 = sum(var_1 + var_2 + var_3 + var_4)
    }
    
    return(c(goal_1))
    
}

FUNwrapper <- function(x1,x2,x3,x4) list(
    "Score"=bayesian_function(x1=x1,
                              x2=x2,
                              x3=x3,
                              x4=x4))

bounds <- list(x1 =c(20,40), x2 = c(30,45), x3 = c(10,20), x4 = c(10,50))


optObj <- bayesOpt(FUN = FUNwrapper, bounds = bounds , initPoints = 10 , acq = "ei" , iters.n = 2 , gsPoints = 25 )
```
What do you think of this? Here, I have added a constraint that says "var_1" can not be greater than 0.6 by assigning "goal_1" a very large number when this happens.

Let me know your thoughts.
Thanks

**Comment by AnotherSamWilson** [comment]
This will kind of work, but the process will waste time discovering the boundary. A much better method would be to simply encode constraints into the acquisition function somehow. I plan on working on this problem this week.

**Comment by swaheera** [comment]
thank you for your reply! I look forward to hearing from you again! 

Some questions:

1) Do you know if more people are using your library for hyperparameter optimization within machine learning algorithms? Or they are using it more in the classical sense?

2) Have you ever looked into the "mlrMBO" library before (https://cran.r-project.org/web/packages/mlrMBO/index.html)? 

3) Do you know of any use cases where your library was used for real world projects? How were the reviews? Have you ever tried using this library on real world data before?

Thanks for everything!

**Comment by swaheera** [comment]
Re (Waste Time): But you still think that writing constraints this way might be correct?
