### ISSUE TITLE
Re-use of figures in the documentation

### ISSUE THREAD

**Issue by nathanchara** [AnotherSamWilson/ParBayesianOptimization#44]
I'm preparing proceedings of the Seas-Fee winter school (http://nccr-planets.ch/saasfee2020/). One of the authors would like to reproduce a figure of the ParBayesianOptimization documentation with the acknowledgement: "Figure from the documentation of the ParBayesianOptimisation package by Sam Wilson.". Would that be ok with you?

Here's my homepage if you want further information. https://www.unige.ch/sciences/astro/exoplanets/en/team/scientific-collaborators/nathan-hara/

Thanks!

**Comment by samFarrellDay** [comment]
Sure, go ahead. (This is the work account of @AnotherSamWilson)
