### ISSUE TITLE
Parallelization using SLURM 

### ISSUE THREAD

**Issue by royr2** [AnotherSamWilson/ParBayesianOptimization#46]
Hi Sam, 
Amazing package! Is there a way to run things in parallel using a SLURM cluster? I haven't been able to figure this bit out so far. 

Thanks!

**Comment by AnotherSamWilson** [comment]
Hmmm I am not familiar with SLURM, but a brief glance at the documentation didn't make me optimistic. It looks like `rslurm` has its own wrappers that take care of most of the setup, while this package uses foreach:

```
  # Define processing function
  `%op%` <- ParMethod(parallel)
  if(parallel) Workers <- getDoParWorkers() else Workers <- 1

  # Run initialization
  if (verbose > 0) cat("\nRunning initial scoring function",nrow(initGrid),"times in",Workers,"thread(s)...")
  sink(file = sinkFile)
  tm <- system.time(
    scoreSummary <- foreach(
        iter = 1:nrow(initGrid)
      , .options.multicore = list(preschedule=FALSE)
      , .combine = list
      , .multicombine = TRUE
      , .inorder = FALSE
      , .errorhandling = 'pass'
      #, .packages ='data.table'
      , .verbose = FALSE
    ) %op% {
```

Personally I never really liked this implementation, but it was the only one I could find at the time that would work with this package's requirements. I'll take a look at SLURM and see what the advantages are.

**Comment by royr2** [comment]
Thank you for the quick response. Do let me know if there is a workaround I could use. In the meantime, I will close this issue. Thanks again for the package!
