### ISSUE TITLE
The number of iterations to use minUtility as the stop indicator

### ISSUE THREAD

**Issue by yhyates** [AnotherSamWilson/ParBayesianOptimization#51]
When the iters.n parameter is not set, iters.k = 1, parallel = FALSE, only keep timeLimit = Inf, minUtility = 0 in otherHalting, ParBayesianOptimization (PBO) only tries a fixed 3 additional iterations to stop optimization, so the number of PBO iterations to try is (number of initPoints plus 3). When different values of initPoints are set, the global optimal value obtained according to the minimum utility limit condition is inconsistent. How to optimize this situation, is to increase the number of initPoints, or set the iters.n parameter? Thanks for any help and answers.

**Comment by yhyates** [comment]
Thank you very much for your reply! The point I don't understand properly is why only 3 extra iterations are always attempted when utilizing the minimum utility limit? So the total number of iterations is initPoints plus 3. Appreciate any help.

**Comment by AnotherSamWilson** [comment]
The process should always run `initPoints + iters.n` iterations total, unless some other halting criteria is met. If you are seeing something different, can you post a reproducible example?
