### ISSUE TITLE
"Noise could not be added to find unique parameter set. Stopping process and returning results so far."

### ISSUE THREAD

**Issue by SanyuR132** [AnotherSamWilson/ParBayesianOptimization#54]
Hello! I keep getting this error while tuning my model which causes the optimization to stop early. Any ideas on what might be causing it? My model only operates on discrete data, could that be related to it?

**Comment by AnotherSamWilson** [comment]
This usually happens if your inputs are all integers, and the process has already tried all of the integers around the next search point. Can you post your bounds here?

**Comment by SanyuR132** [comment]
Yup! I'm only optimizing for one hyperparameter: `latent_size = c(2L, args$max_latent_size)`
