### ISSUE TITLE
Using ParBayesianOptimization for regression problem in R (minimizing rmse)

### ISSUE THREAD

**Issue by grzechowiak** [AnotherSamWilson/ParBayesianOptimization#8]
Hello,
thanks for the package! I went through your GitHub example and I have tried to implement it to the regression case. I created an issue on StackOverflow but I realized posting it here might have more sense. 
I paste the link to the issue below: 
https://stackoverflow.com/questions/61031444/using-parbayesianoptimization-for-regression-problem-in-r-minimizing-rmse

thanks!

**Comment by AnotherSamWilson** [comment]
ParBayesianOptimization will maximize the function you provide it, to change your problem to a maximization one, just multiply the RMSE (Score) being output by -1.
